/*
 * This file is generated by jOOQ.
*/
package com.example.demo.jooq.domain;


import com.example.demo.jooq.domain.tables.Comments;
import com.example.demo.jooq.domain.tables.Posts;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Springbootjooq extends SchemaImpl {

    private static final long serialVersionUID = 836116115;

    /**
     * The reference instance of <code>springbootjooq</code>
     */
    public static final Springbootjooq SPRINGBOOTJOOQ = new Springbootjooq();

    /**
     * The table <code>springbootjooq.comments</code>.
     */
    public final Comments COMMENTS = com.example.demo.jooq.domain.tables.Comments.COMMENTS;

    /**
     * The table <code>springbootjooq.posts</code>.
     */
    public final Posts POSTS = com.example.demo.jooq.domain.tables.Posts.POSTS;

    /**
     * No further instances allowed
     */
    private Springbootjooq() {
        super("springbootjooq", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Comments.COMMENTS,
            Posts.POSTS);
    }
}
