/*
 * This file is generated by jOOQ.
*/
package com.example.demo.jooq.domain;


import com.example.demo.jooq.domain.tables.Comments;
import com.example.demo.jooq.domain.tables.Posts;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in springbootjooq
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>springbootjooq.comments</code>.
     */
    public static final Comments COMMENTS = com.example.demo.jooq.domain.tables.Comments.COMMENTS;

    /**
     * The table <code>springbootjooq.posts</code>.
     */
    public static final Posts POSTS = com.example.demo.jooq.domain.tables.Posts.POSTS;
}
